#!/bin/bash
set -e
export SSL_CERT_FILE=/Applications/PPCMC.app/certs/cacert.pem
export REQUESTS_CA_BUNDLE=/Applications/PPCMC.app/certs/cacert.pem
rm -rf /Library/WebServer/Documents/ppcmcw/tmp/*

/Applications/PPCMC.app/bin/python2.7 /Applications/PPCMC.app/bin/youtube-dl --prefer-ffmpeg --ffmpeg-location=/Applications/PPCMC.app/bin/ffmpeg -f 133+140 -o /Library/WebServer/Documents/ppcmcw/tmp/"%(title)s.%(ext)s" $1

basefile=$(ls -1 /Library/WebServer/Documents/ppcmcw/tmp/ | sed -e 's/\.mp4$//')  

/Applications/PPCMC.app/bin/ffmpeg -i "/Library/WebServer/Documents/ppcmcw/tmp/$basefile.mp4" -qscale 0 "/Library/WebServer/Documents/ppcmcw/tmp/$basefile.mpeg" 2>&1

cp "/Library/WebServer/Documents/ppcmcw/tmp/$basefile.mpeg" "/Library/WebServer/Documents/ppcmcw/dl/$basefile.mpeg"
rm -rf /Library/WebServer/Documents/ppcmcw/tmp/*